<template>
  <div class="doers-view">
    <h1>Doers</h1>
    <p>Manage your doers here.</p>
    <DoerForm
      :first-name="newDoer.firstName"
      :last-name="newDoer.lastName"
      mode="create"
      @update:first-name="newDoer.firstName = $event"
      @update:last-name="newDoer.lastName = $event"
      @submit-form="handleDoerSubmit"
    />
    <DoerTable />
    <!-- Display submitted doers or manage state here -->
    <div v-if="submittedDoers.length > 0" class="submitted-doers">
      <h2>Submitted Doers:</h2>
      <ul>
        <li v-for="(doer, index) in submittedDoers" :key="index">
          {{ doer.firstName }} {{ doer.lastName }}
        </li>
      </ul>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import DoerForm from '@/components/DoerForm.vue';
import DoerTable from '@/components/DoerTable.vue';
import type { Doer } from '@/models/doer.model';

interface NewDoer {
  firstName: string;
  lastName: string;
}

const newDoer = ref<NewDoer>({ firstName: '', lastName: '' });
const submittedDoers = ref<Doer[]>([]); // This will eventually be managed by a store

const handleDoerSubmit = (doerData: Omit<Doer, 'id'>) => {
  // For now, just add to a local list. Later, this will interact with a store.
  // A proper ID would be generated by a backend or a more robust client-side strategy.
  const doerWithId: Doer = { ...doerData, id: Date.now() };
  submittedDoers.value.push(doerWithId);
  newDoer.value = { firstName: '', lastName: '' }; // Reset form
  console.log('Doer submitted:', doerWithId);
};
</script>

<style scoped>
.doers-view {
  padding: 1rem;
}

.submitted-doers {
  margin-top: 1.5rem;
  padding: 1rem;
  border: 1px solid #e0e0e0;
  border-radius: 4px;
  background-color: #f9f9f9;
}

.submitted-doers h2 {
  margin-top: 0;
}

.submitted-doers ul {
  list-style-type: none;
  padding: 0;
}

.submitted-doers li {
  padding: 0.25rem 0;
}
</style>
